### ISSUE TITLE
// m mod 4 (start from 00)

### ISSUE THREAD

**Issue by MaksimKoster** [ZhukDmitryOlegovich/logica-2#1]
00 0 -> 01 " R

01 0 -> 17 0 L
17 " -> . 0 .

01 1 -> 02 " R
02 0 -> 03 0 L
03 " -> 04 1 L
04 " -> . 0 .

02 1 -> 05 " R
05 0 -> 06 0 L
06 " -> 07 1 L
07 " -> 08 1 L
08 " -> . 0 .

05 1 -> 09 " R
09 0 -> 10 0 L
10 " -> 11 1 L
11 " -> 12 1 L
12 " -> 13 1 L
13 " -> . 0 .

09 1 -> 14 " R
14 0 -> 15 0 L
15 " -> . 0 .

14 1 -> 01 1 .

**Comment by ZhukDmitryOlegovich** [comment]
некорректно
```
00 -> 00
010 -> 010
0110 -> 0110
01110 -> 01110
011110 -> 011110
```
![image](https://user-images.githubusercontent.com/93006259/149812773-2f9271e5-5a9c-4e6b-9a9c-a8f25072f4f8.png)

**Comment by ZhukDmitryOlegovich** [comment]
лучше бы в следующих раз начинать со стандартных 01
